# Generated by Django 2.2.6 on 2019-12-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcomes',
            name='connection_to_domestic_violence_services',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='outcomes',
            name='engagement_in_ongoing_domestic_violence_services',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
